# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.

name: Brakeman

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/brakeman.yml'
      - '.ruby-version'
      - 'ruby-on-rails/.ruby-version'
      - 'ruby-on-rails/Gemfile'
      - 'ruby-on-rails/Gemfile.lock'
      - 'ruby-on-rails/Rakefile'
      - 'ruby-on-rails/**/*.rb'
      - 'ruby-on-rails/**/*.rake'
      - 'ruby-on-rails/**/*.yml'
      - 'ruby-on-rails/**/*.js'
      - 'ruby-on-rails/**/*.css'
      - 'ruby-on-rails/**/*.html.erb'
      - 'ruby-on-rails/**/*.csv'
      - 'ruby-on-rails/**/*.json'
  pull_request:
    paths:
      - '.github/workflows/brakeman.yml'
      - '.ruby-version'
      - 'ruby-on-rails/.ruby-version'
      - 'ruby-on-rails/Gemfile'
      - 'ruby-on-rails/Gemfile.lock'
      - 'ruby-on-rails/Rakefile'
      - 'ruby-on-rails/**/*.rb'
      - 'ruby-on-rails/**/*.rake'
      - 'ruby-on-rails/**/*.yml'
      - 'ruby-on-rails/**/*.js'
      - 'ruby-on-rails/**/*.css'
      - 'ruby-on-rails/**/*.html.erb'
      - 'ruby-on-rails/**/*.csv'
      - 'ruby-on-rails/**/*.json'

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Gem Dependencies
        working-directory: ./ruby-on-rails
        run: bundle install
      - name: Run Brakeman
        working-directory: ./ruby-on-rails
        run: bundle exec brakeman --no-pager
